name: Connect4 Game

on:
  issues:
    types: [opened]

jobs:
  connect4:
    if: contains(github.event.issue.title, 'connect4')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Play Connect 4
        uses: lowlighter/metrics@latest
        with:
          filename: connect4.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_connect4: yes
          plugin_connect4_duration: 1
