name: Connect4 Game

on:
  issues:
    types: [opened]

jobs:
  connect4:
    if: contains(github.event.issue.title, 'connect4')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Play Connect4
        uses: Platane/snk@v3
        with:
          github_user_name: Akshat09Yadav
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
